### ISSUE TITLE
Demo site: wrong URL for Pagespeed Insights button on non-AMP non_bento

### ISSUE THREAD

**Issue by schlessera** [rtCamp/blocks-bento-variations#18]
On the demo site, the `PageSpeed Insights Results` button has a bad URL for the `Non AMP + Non Bento Block` variation.

Instead of linking to the Pagespeed Insights results, the button just links to the site it is on.

**Comment by maitreyie-chavan** [comment]
@schlessera Thank you for reporting, this is now fixed ✔️ 

> https://bento.rtcamp.com/non-amp-and-non-bento-block/
